### ISSUE TITLE
Error NG6002 on Angular 9 with Ivy

### ISSUE THREAD

**Issue by andreialecu** [aitboudad/ngx-loading-bar#151]
Been getting this error while compiling with angular 9 with Ivy enabled:

```
ERROR in Failed to compile entry-point @ngx-loading-bar/http-client (es2015 as esm2015) due to compilation errors:
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of LoadingBarHttpClientModule, but could not be resolved to an NgModule class

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6003: Appears in the NgModule.exports of LoadingBarHttpClientModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

2801 export declare class HttpClientModule {
```

**Comment by andreialecu** [comment]
Based on this comment, maybe it's just a matter of updating `ng-packagr` and rebuilding:

https://github.com/angular/angular/issues/35255#issuecomment-586626665

**Comment by aitboudad** [comment]
Hi, could you please use `5.0.0-alpha.0` version and let me know if that fixes the issue. Thanks!

**Comment by ricardosaracino** [comment]
It was working on 9.0.2 but i went to 9.0.3 and it def gave me some problems. I rolled back, @andreialecu, did yo get the alpha working?

**Comment by andreialecu** [comment]
I have just tried updating to `5.0.0-alpha.0` but I'm seeing the exact same error. I'm on angular 9.0.2, and have been since opening the issue.

I've just also tried angular 9.0.4 with `5.0.0-alpha.0` and I'm seeing the same problem.

**Comment by andreialecu** [comment]
I have just deleted my `yarn.lock` and `node_modules` to see what happens if I go to the latest versions of everything and I'm seeing a different error:

```
ERROR in Failed to compile entry-point @ngx-loading-bar/http-client (es2015 as esm2015) due to compilation errors:
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of LoadingBarHttpClientModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
../../node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6003: Appears in the NgModule.exports of LoadingBarHttpClientModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2801 export declare class HttpClientModule {
```

**Comment by andreialecu** [comment]
The error above is just a reporting change in angular 9.0.4 as per this commit: https://github.com/angular/angular/commit/2d89b5d13d22cdb50c09217c54932c29484386b0

I still think updating `ng-packagr` here: https://github.com/aitboudad/ngx-loading-bar/blob/master/package.json#L56 to ^9.0.2 and republishing might fix it.

**Comment by aitboudad** [comment]
updated deps to `v9` in `5.0.0-alpha.1`

**Comment by aitboudad** [comment]
let me know if this works on your side to release a stable release (`v5`) asap.

**Comment by ricardosaracino** [comment]
This is working for me now 😐
```
  "dependencies": {
    "@angular/animations": "~9.0.4",
    "@angular/common": "~9.0.4",
    "@angular/compiler": "~9.0.4",
    "@angular/core": "~9.0.4",
    "@angular/forms": "~9.0.4",
    "@angular/localize": "^9.0.4",
    "@angular/platform-browser": "~9.0.4",
    "@angular/platform-browser-dynamic": "~9.0.4",
    "@angular/router": "~9.0.4",
    "@coreui/angular": "^2.9.0",
    "@coreui/coreui": "^2.1.16",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/http-client": "^4.2.0",
    "class-transformer": "^0.2.3",
```

**Comment by ricardosaracino** [comment]
i can server this config but no bar is visible

```
  "dependencies": {
    "@angular/animations": "~9.0.4",
    "@angular/common": "~9.0.4",
    "@angular/compiler": "~9.0.4",
    "@angular/core": "~9.0.4",
    "@angular/forms": "~9.0.4",
    "@angular/localize": "^9.0.4",
    "@angular/platform-browser": "~9.0.4",
    "@angular/platform-browser-dynamic": "~9.0.4",
    "@angular/router": "~9.0.4",
    "@coreui/angular": "^2.9.0",
    "@coreui/coreui": "^2.1.16",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ngx-loading-bar/core": "5.0.0-alpha.0",
    "@ngx-loading-bar/http-client": "5.0.0-alpha.0",

**Comment by aitboudad** [comment]
@ricardosaracino use `5.0.0-alpha.1` else I may need a reproduction example https://stackblitz.com/edit/angular-p4ztzx

**Comment by andreialecu** [comment]
@ricardosaracino are you sure you're compiling with Ivy enabled? This problem is about Ivy. Without Ivy it works for me too. Try with `"enableIvy": true` in `tsconfig.json/angularCompilerOptions`

@aitboudad I've seen your commit, but the `>=7.0.0` peer dependency range would already match angular 9 so I don't see much help with that. Also you didn't seem to update `ng-packagr` which people pointed out to solving the problem in other packages. Is there any reason for that?

`5.0.0-alpha.1` did not solve the issue for me on Ivy.

**Comment by andreialecu** [comment]
@aitboudad I've tried creating a simple repro but it seems that in a fresh project it works with Ivy, so it just happens in my main project. 

The error is always related to `Failed to compile entry-point @ngx-loading-bar/http-client (es2015 as esm2015) due to compilation errors:` though which is very weird.

I'll try to narrow it down, but it may be some sort of Angular 9 bug instead. I'm also using yarn workspaces in my main project.

**Comment by andreialecu** [comment]
I've managed to create a repro and opened https://github.com/angular/angular/issues/35747 

It only happens with a particular layout of yarn workspaces.

**Comment by ricardosaracino** [comment]
@andreialecu i do not have that compilation option on
